# 说明 创建:
mkdir ~/.pip
vim ~/.pip/pip.conf

# 填入内容：
[global]
index-url = http://mirrors.aliyun.com/pypi/simple/
# index-url = http://mirrors.cloud.tencent.com/pypi/simple/
# index-url = https://mirrors.tencentyun.com/pypi/simple
trusted-host = mirrors.aliyun.com
# trusted-host = mirrors.cloud.tencent.com
# trusted-host = mirrors.tencentyun.com

[install]
trusted-host=mirrors.aliyun.com
